# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  name: 'AgentForAgile'
  demands: 
   - mvn
  
 
steps:

    




- task: Maven@4
  inputs:
     mavenPomFile: 'pom.xml'
     testResultsFiles: '**surefire-reports/TEST-*.xml'
     javaHomeOption: JDKVersion
     mavenVersionOption: Default
     
     
  
- task: CopyFiles@2
  inputs:
     Contents: '**/target/*.jar'
     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
     ArtifactName: 'drop'
     publishLocation: 'Container'
- task: UniversalPackages@0
  displayName: 'Publish .jar to Azure Artifacts (Universal Package)'
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: 'maven'
    
    


